
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/yourdbname

  frontend:
    build: ./newfrontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    ports:
      - "27017:27017"
